// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpDXkJCWawYgVR46RkHz7Iy1JDd-gHHj4',
    appId: '1:683499442974:web:326a7696f1f8f4e0a92f0f',
    messagingSenderId: '683499442974',
    projectId: 'reward-system-717de',
    authDomain: 'reward-system-717de.firebaseapp.com',
    storageBucket: 'reward-system-717de.appspot.com',
    measurementId: 'G-6EZ6SVKEYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0FhmfSkhXGQaElIv1uYUfvXbolkdkB04',
    appId: '1:683499442974:android:45742c5ab55bddaaa92f0f',
    messagingSenderId: '683499442974',
    projectId: 'reward-system-717de',
    storageBucket: 'reward-system-717de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGgklnodRUQuN-dAN1E_-TgSe5QLmcDdA',
    appId: '1:683499442974:ios:8c659220c00eb1c6a92f0f',
    messagingSenderId: '683499442974',
    projectId: 'reward-system-717de',
    storageBucket: 'reward-system-717de.appspot.com',
    iosClientId: '683499442974-n9p145fmeg95g9idrth4nbs9qpu2t6i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.rewardsystem',
  );
}
